### ISSUE TITLE
[C++11][言語機能]関数のdefault/delete宣言

### ISSUE THREAD

**Issue by Peter9606** [cpprefjp/site#537]
In the last of [仕様] block, there's「非静的メンバ変数が削除定義された特殊メンバ関数を持つ場合、その変数をメンバとして持つクラス…」.  I'm wondering in what kind of situation a member variable can hold/point to a deleted member function? It would be more easier to understand ff there's a sample code.

**Comment by ToruNiina** [comment]
In the following case,

```cpp
struct X {std::unique_ptr<int> i_ptr;};
```

`std::unique_ptr` has "deleted member function"s like `unique_ptr::operator=(const unique_ptr&) = delete`. So `X::operator=(const X&)` is deleted implicitly because the default definition that uses `unique_ptr::operator=(const unique_ptr&)` would be ill-formed.

I also feel the sentence is a bit hard to figure out. I propose rewriting it as「非静的メンバ変数の特殊メンバ関数が削除定義されているとき、その変数をメンバとして持つクラスのその特殊メンバ関数は、暗黙的に削除定義される。」.

**Comment by Peter9606** [comment]
@ToruNiina  Thank you for quick response. It's now clear.
